site_name: GO learning
site_url: https://marcoaalmeida.github.io/sandbox/
nav:
  - Home: index.md
  - mkDocs: mkdocs.md
  - Github Actions: actions.md
  - protobuf: protobuf.md
  - sorting: protobuf.md
  - testing: protobuf.md

theme:
  name: material
  icon:
    logo: fontawesome/brands/golang
  palette:
    scheme: slate
    primary: teal
    accent: lime
  font:
    code: Roboto Mono