site_name: GO learning
site_url: https://marcoaalmeida.github.io/sandbox/
nav:
  - Home: index.md
  - Actions: actions.md
  - About: about.md
theme:
  name: mkdocs
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode