spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:mb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    username: SA
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml

