spring:
  application:
    name: mb
  profiles:
    active: dev

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

jwt:
  private:
    key: "classpath:app.key"
  public:
    key: "classpath:app.pub"

api:
  version: "1.0-SNAPSHOT"
  server:
    url: "http://localhost"
  description: "The User API is used to create, update, and delete users. Users can be created with or without an associated account. If an account is created, the user will be granted the <strong>ROLE_USER</strong> role. If an account is not created, the user will be granted the <b>ROLE_USER</b> role."

openai:
  apikey: <placeholder>
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
              'env',
              'health',
              'info',
              'logfile',
              'loggers',
              'threaddump',
              'liquibase',
          ]
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
