name: build-and-deploy-s3
run-name: ${{ github.actor }} builds project with GitHub Actions
on:
  push:
    paths:
      mlearn/**
jobs:
  build-nuxt-then-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: cd mlearn && yarn install && npm run generate
      - run: cd mlearn && ls -al
      - run: aws s3 sync mlearn/.output/public s3://mlearn.marcoalmeida.dev.br --delete
